<a href="https://colab.research.google.com/github/VardanDavtyan/ML-DL/blob/main/Tensorflow4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import tensorflow as tf

In [ ]:
class DenseNN(tf.Module):

  def __init__(self, outputs):
    super().__init__()
    self.outputs = outputs
    self.fl_init = False

  def __call__(self, x):
    if not self.fl_init:
      self.w = tf.random.truncated_normal((x.shape[-1], self.outputs), stddev=0.1, name="w")
      self.b = tf.zeros([self.outputs], dtype=tf.float32, name="b")

      self.w = tf.Variable(self.w)
      self.b = tf.Variable(self.b)

      self.fl_init = True
    y = x @ self.w + self.b
    return y





In [ ]:
model = DenseNN(1) #1 is neurons count

x_train = tf.random.uniform(minval=0, maxval=10, shape=(100, 2))
y_train = [a + b for a, b in x_train]

loss = lambda x, y: tf.reduce_mean(tf.square(x - y))
opt = tf.optimizers.Adam(learning_rate=0.01)

EPOCHS = 50
for n in range(EPOCHS):
  for x, y in zip(x_train, y_train):
    x = tf.expand_dims(x, axis=0)
    y = tf.constant(y, shape=(1, 1))

    with tf.GradientTape() as tape:
      f_loss = loss(y, model(x))

    grads = tape.gradient(f_loss, model.trainable_variables)
    opt.apply_gradients(zip(grads, model.trainable_variables))

print(y_train)
print(model.trainable_variables)
print(model(tf.constant([[1.0, 2.0]])))

[<tf.Tensor: shape=(), dtype=float32, numpy=13.259174>, <tf.Tensor: shape=(), dtype=float32, numpy=8.366447>, <tf.Tensor: shape=(), dtype=float32, numpy=12.851585>, <tf.Tensor: shape=(), dtype=float32, numpy=8.095037>, <tf.Tensor: shape=(), dtype=float32, numpy=12.607598>, <tf.Tensor: shape=(), dtype=float32, numpy=7.403388>, <tf.Tensor: shape=(), dtype=float32, numpy=18.49841>, <tf.Tensor: shape=(), dtype=float32, numpy=9.951767>, <tf.Tensor: shape=(), dtype=float32, numpy=10.722079>, <tf.Tensor: shape=(), dtype=float32, numpy=7.310716>, <tf.Tensor: shape=(), dtype=float32, numpy=5.7290792>, <tf.Tensor: shape=(), dtype=float32, numpy=12.834086>, <tf.Tensor: shape=(), dtype=float32, numpy=12.572389>, <tf.Tensor: shape=(), dtype=float32, numpy=5.777631>, <tf.Tensor: shape=(), dtype=float32, numpy=8.6195135>, <tf.Tensor: shape=(), dtype=float32, numpy=14.07619>, <tf.Tensor: shape=(), dtype=float32, numpy=8.830989>, <tf.Tensor: shape=(), dtype=float32, numpy=10.676219>, <tf.Tensor: shape=